# Generated by Django 3.1.2 on 2020-12-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20201211_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='region',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='apellido',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nserie',
            field=models.TextField(max_length=15),
        ),
    ]
