# Generated by Django 3.1.2 on 2020-12-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_auto_20201211_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='telefono',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
