# Generated by Django 3.1.2 on 2020-12-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_formulario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='email',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='rut',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='telefono',
            field=models.TextField(default=None, max_length=20),
        ),
    ]
